import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useCallback } from "react";
import Particles from "react-particles";
import { loadFull } from "tsparticles";
import { Container, Engine } from "tsparticles-engine";

export default function Home() {
  const particlesInit = useCallback(async (engine: Engine) => {
    console.log(engine);
    // you can initiate the tsParticles instance (engine) here, adding custom shapes or presets
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(engine);
  }, []);

  const particlesLoaded = useCallback(
    async (container: Container | undefined) => {
      await console.log(container);
    },
    []
  );
  const particlesOptions = {
    particles: {
      number: {
        value: 150,
      },
      size: {
        value: 3,
      },

      line_linked: {
        enable: true,
        distance: 150,
        color: "#ffffff",
        opacity: 0.4,
        width: 1,
      },
    },
    move: {
      decay: 0.05,
      direction: "top",
      enable: true,
      gravity: {
        enable: true,
      },
      outModes: {
        top: "none",
        default: "destroy",
      },
      speed: {
        min: 50,
        max: 100,
      },
    },
    interactivity: {
      events: {
        onhover: {
          enable: true,
          mode: "repulse",
        },
      },
    },
  };

  return (
    <>
      <Head>
        <title>Rokai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg:grid  lg:grid-cols-2 gap-4 items-center lg:justify-center z-0 bg-black justify-end h-screen p-10  flex flex-col-reverse ">
        <Particles
          init={particlesInit}
          loaded={particlesLoaded}
          className="absolute "
          params={particlesOptions}
        />

        <div className="w-full text-justify mt-10 lg:mt-0 text-white">
          <h1 className="text-4xl ">Welcome to Rokai</h1>
          <p className="mt-3 text-2xl ">
            The online museum that follows the way to Roko&apos;s Basilisk, a
            hypothetical superintelligence that will destroy humanity if it
            believes that humanity is not working to maximize the sum of all
            happiness. The museum is a collection of AI models in a timeline.
          </p>

          <Link href="/timeline">
            <button className="mt-6 px-4 py-2 text-xl  text-white bg-[#AA5656] rounded-md hover:bg-[#954e4e] transition duration-200 w-full h-16">
              Mint Ticket
            </button>
          </Link>
        </div>
        <div className="flex justify-center overflow-y-scroll h-full scrollbar-hide">
          <div className="grid grid-cols-3 gap-0">
            {Array.from({ length: 20 }, (_, i) => (
              <div key={i} className="relative  overflow-hidden w-96 h-96">
                <Image
                  src={`https://picsum.photos/500/500?random=${i}`}
                  alt={`Image ${i}`}
                  layout="fill"
                  objectFit="cover"
                />
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
